#!/bin/sh

getvol() {
	pamixer --get-volume
}

setvol() {
	# Set volume.
	pamixer --set-volume "$1"
	# Update eww.
	eww update volume-value="$(getvol)"
}

status() {
	pamixer --get-mute
}

toggle() {
	# Toggle mute.
	pamixer --toggle-mute
	# Update eww.
	if [[ $(eww get volume-mute) == "false" ]]; then
		eww update volume-mute="true"
	else
		eww update volume-mute="false"
	fi
}

case "$1" in
	"--get-volume") getvol;;
	"--set-volume") setvol $2;;

	"--status-mute") status;;
	"--toggle-mute") toggle;;
esac
