" Turn on syntax highlighting by default.
syntax on

set number
set relativenumber

set mouse=a

set tabstop=4
set shiftwidth=0

set smarttab
set autoindent

" Compile and run cpp script.
autocmd FileType cpp nnoremap <F11> :w<CR> :!g++ -std=c++17 -Wall -o %:r.out % && ./%:r.out<CR>
