[ids]

*

################################################################################

[main]
# Make <Caps> behave like <Esc> when tapped and <Ctrl> when held.
capslock = overload(capslock, esc)

################################################################################

[capslock:C]
# Make <Caps-;> behave like <Ctrl-a> (for GNU screen and tmux).
; = C-a
