#!/usr/bin/env bash

if [[ $( xrandr | grep -c " connected " ) > 1 ]]; then
	bspc monitor "^1" -d 1 2 3 4 5 6 7 8
	bspc monitor "^2" -d 9
else
	bspc monitor "^1" -d 1 2 3 4 5 6 7 8 9
fi

# Add gaps between windows.
bspc config window_gap 16

# No borders. Keep it minimal.
bspc config border_width 0

# Set rules.
bspc rule -a "KeePassXC" state="floating"
bspc rule -a "mpv" desktop="^8" state="floating"
bspc rule -a "qBittorrent" state="floating"
bspc rule -a "steam" desktop="^9" state="floating"

pgrep -x "sxhkd" || sxhkd &
pgrep -x "picom" || picom &
