#!/usr/bin/env bash

# Set monitor numbers & names.
bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true

# Size of the gap that separates windows.
bspc config window_gap          10

# Window border width.
bspc config border_width        0

# Rules.
bspc rule -a kooha state=floating
bspc rule -a Rofi state=floating


# Map keys with sxhkd.
pgrep -x sxhkd > /dev/null || sxhkd &

# Manage networks with nm-applet.
# nm-applet

# Manage bluetooth with blueman-applet.
# blueman-applet

# Composite X windows with picom.
pgrep -x picom > /dev/null || picom &

# Render wallpaper with feh.
feh --bg-fill --no-fehbg "${XDG_CONFIG_HOME:-$HOME/.config}/bspwm/wall.png"

# Render taskbar with polybar.
bash "${XDG_CONFIG_HOME:-$HOME/.config}/polybar/launch.sh" darktide

# Host firefox homepage with http-server.
http-server "${XDG_CONFIG_HOME:-$HOME/.config}/firefox/homepages/Chevron"
